example = input('example.com')
one= input('example.1')
two =input('example.2')
three =input('example.3')
four= input('example.4')
five= input('example.5')
tested_link_list=[]
tested_link_list.append(one)
tested_link_list.append(two)
tested_link_list.append(three)
tested_link_list.append(four)
tested_link_list.append(five)
print('tested pages:',tested_link_list)